clase/urls.py
from django.urls import path

from clase.views import ClaseGenericView,ClaseCreateView,ClaseDetailView,ClaseDeleteView

app_name = 'clase'
urlpatterns = [
    path('', ClaseGenericView.as_view(), name='list_clase'),
    path('new', ClaseCreateView.as_view(), name='new_clase'),
    path('<pk>/', ClaseDetailView.as_view(), name='detail_clase'),
    path('delete/<pk>/', ClaseDeleteView.as_view(), name='delete_clase'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('clase/', include('clase.urls')),
    path('escuela/', include('escuela.urls')),
]

escuela/urls.py
from django.urls import path

from escuela.views import *

app_name = 'escuela'
urlpatterns = [
    path('', EscuelaGenericView.as_view(), name='list_escuela'),
    path('new', EscuelaCreateView.as_view(), name='new_escuela'),
    path('<pk>/', EscuelaDetailView.as_view(), name='detail_escuela'),
    path('delete/<pk>/', EscuelaDeleteView.as_view(), name='delete_escuela'),
]

student/urls.py
from django.urls import path

from student.views import *

app_name = 'student'
urlpatterns = [
    path('', StudentGenericView.as_view(), name='list'),
    path('new', StudentCreateView.as_view(), name='new'),
    path('<pk>/', StudentDetailView.as_view(), name='detail'),
    path('delete/<pk>/', StudentDeleteView.as_view(), name='delete'),
]

clase/models.py
from django.db import models

from escuela.models import Escuela


class Clase(models.Model):
    name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)
    description = models.TextField(max_length=200)
    active = models.BooleanField(default=True)
    escuela= models.ForeignKey(
        Escuela,
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return f'{self.name}'

escuela/models.py
from django.db import models

class Escuela(models.Model):
    name = models.CharField(max_length=30)
    address = models.TextField(max_length=200)
    district = models.CharField(max_length=30)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}'

student/models.py
from django.db import models

from clase.models import Clase
from escuela.models import Escuela


class Student(models.Model):
    name = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    address = models.TextField(max_length=200)
    dob = models.DateField()
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=20)
    active = models.BooleanField(default=True)
    escuela = models.ForeignKey(
        Escuela,
        related_name='student',
        on_delete=models.SET_NULL,
        null=True
    )
    clase = models.ManyToManyField(
        Clase,
        related_name='clase'
    )

    def __str__(self):
        return f'{self.name} {self.lastname} - {self.email}'

clase/views.py
from django.views.generic import CreateView, DetailView, DeleteView,ListView

from clase.models import Clase


class ClaseGenericView(ListView):
    model = Clase
    context_object_name = 'clases'


class ClaseCreateView(CreateView):
    model = Clase
    fields = '__all__'
    success_url = '/clase/'


class ClaseDetailView(DetailView):
    queryset = Clase.objects.all()


class ClaseDeleteView(DeleteView):
    model = Clase
    success_url = '/clase/'

escuela/views.py
from django.views.generic import ListView, CreateView, DetailView, DeleteView

from escuela.models import Escuela


class EscuelaGenericView(ListView):
    model = Escuela
    context_object_name = 'escuelas'


class EscuelaCreateView(CreateView):
    model = Escuela
    fields = '__all__'
    success_url = '/escuela/'


class EscuelaDetailView(DetailView):
    queryset = Escuela.objects.all()


class EscuelaDeleteView(DeleteView):
    model = Escuela
    success_url = '/escuela/'

student/views.py
from django.views.generic import ListView, CreateView, DetailView, DeleteView

from student.models import Student


class StudentGenericView(ListView):
    model = Student
    context_object_name = 'students'


class StudentCreateView(CreateView):
    model = Student
    fields = '__all__'
    success_url = '/student/'


class StudentDetailView(DetailView):
    queryset = Student.objects.all()


class StudentDeleteView(DeleteView):
    model = Student
    success_url = '/student/'

clase/templates/clase/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'student:list' %}">CRUD</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'escuela:list_escuela' %}">Escuela</a>
                <a class="nav-link" href="{% url 'clase:list_clase' %}">Clases</a>
                <a class="nav-link" href="{% url 'student:list' %}">Estudiantes</a>
            </div>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container" id="app">
    {% block content %}
    {% endblock %}
</div>
<!-- /.container -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

clase/templates/clase/clase_detail.html
{% extends 'student/base.html' %}

{% block content %}
<ul class="list-group m-3">
    <li class="list-group-item">{{object.name}}</li>
    <li class="list-group-item">{{object.subject}}</li>
    <li class="list-group-item">{{object.description}}</li>
    <form method="post" action="{% url 'clase:delete_clase' object.id %}">
        {% csrf_token %}
        <li class="list-group-item">
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a href="{% url 'clase:list_clase' %}" class="btn btn-info">Regresar</a>
        </li>
    </form>

</ul>
{% endblock %}

clase/templates/clase/clase_form.html
{% extends 'student/base.html' %}

{% block content %}
<div class="mt-3">
    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary"> Guardar</button>
    </form>
</div>
{% endblock %}

clase/templates/clase/clase_list.html
{% extends 'student/base.html' %}

{% block content %}
<div class="m-3">
    <div class="card">
        <div class="card-header">
            <a href="{% url 'clase:new_clase' %}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Agregar Clase</a>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Nombres</th>
                    <th scope="col">Materia</th>
                    <th scope="col">Description</th>
                    <th scope="col">Acción</th>
                </tr>
                </thead>
                <tbody>
                {% for clase in clases %}
                <tr>
                    <td>{{clase.name}}</td>
                    <td>{{clase.subject}}</td>
                    <td>{{clase.description}}</td>
                    <td class="text-center">
                        <a href="{% url 'clase:detail_clase' clase.id %}">
                            <i class="fa fa-list-alt" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock %}

escuela/templates/escuela/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'student:list' %}">CRUD</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'escuela:list_escuela' %}">Escuela</a>
                <a class="nav-link" href="{% url 'clase:list_clase' %}">Clases</a>
                <a class="nav-link" href="{% url 'student:list' %}">Estudiantes</a>
            </div>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container" id="app">
    {% block content %}
    {% endblock %}
</div>
<!-- /.container -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

escuela/templates/escuela/ecuela_detail.html
{% extends 'student/base.html' %}

{% block content %}
<ul class="list-group m-3">
    <li class="list-group-item">{{object.name}}</li>
    <li class="list-group-item">{{object.subject}}</li>
    <li class="list-group-item">{{object.description}}</li>
    <form method="post" action="{% url 'student:delete_class' object.id %}">
        {% csrf_token %}
        <li class="list-group-item">
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a href="{% url 'student:list_class' %}" class="btn btn-info">Regresar</a>
        </li>
    </form>

</ul>
{% endblock %}

escuela/templates/escuela/escuela_form.html
{% extends 'student/base.html' %}

{% block content %}
<div class="mt-3">
    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary"> Guardar</button>
    </form>
</div>
{% endblock %}

escuela/templates/escuela/escuela_list.html
{% extends 'student/base.html' %}

{% block content %}
<div class="m-3">
    <div class="card">
        <div class="card-header">
            <a href="{% url 'escuela:new_escuela' %}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Agregar Clase</a>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Nombres</th>
                    <th scope="col">Direccion</th>
                    <th scope="col">Distrito</th>
                    <th scope="col">Acción</th>
                </tr>
                </thead>
                <tbody>
                {% for escuela in escuelas %}
                <tr>
                    <td>{{escuela.name}}</td>
                    <td>{{escuela.address}}</td>
                    <td>{{escuela.district}}</td>
                    <td class="text-center">
                        <a href="{% url 'escuela:detail_escuela' escuela.id %}">
                            <i class="fa fa-list-alt" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock %}

student/templates/student/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'student:list' %}">CRUD</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'student:list' %}">Estudiantes</a>
                <a class="nav-link" href="{% url 'student:list_class' %}">Clases</a>
            </div>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container" id="app">
    {% block content %}
    {% endblock %}
</div>
<!-- /.container -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

student/templates/student/class_detail.html
{% extends 'student/base.html' %}

{% block content %}
<ul class="list-group m-3">
    <li class="list-group-item">{{object.name}}</li>
    <li class="list-group-item">{{object.subject}}</li>
    <li class="list-group-item">{{object.description}}</li>
    <form method="post" action="{% url 'student:delete_class' object.id %}">
        {% csrf_token %}
        <li class="list-group-item">
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a href="{% url 'student:list_class' %}" class="btn btn-info">Regresar</a>
        </li>
    </form>

</ul>
{% endblock %}

student/templates/student/class_form.html
{% extends 'student/base.html' %}

{% block content %}
<div class="mt-3">
    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary"> Guardar</button>
    </form>
</div>
{% endblock %}

student/templates/student/class_list.html
{% extends 'student/base.html' %}

{% block content %}
<div class="m-3">
    <div class="card">
        <div class="card-header">
            <a href="{% url 'student:new_class' %}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Agregar Clase</a>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Nombres</th>
                    <th scope="col">Materia</th>
                    <th scope="col">Description</th>
                    <th scope="col">Acción</th>
                </tr>
                </thead>
                <tbody>
                {% for class in classes %}
                <tr>
                    <td>{{class.name}}</td>
                    <td>{{class.subject}}</td>
                    <td>{{class.description}}</td>
                    <td class="text-center">
                        <a href="{% url 'student:detail_class' class.id %}">
                            <i class="fa fa-list-alt" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock %}

student/templates/student/student_detail.html
{% extends 'student/base.html' %}

{% block content %}
<ul class="list-group m-3">
    {{object.escuela.clase}}
    <li class="list-group-item">{{object.name}} {{object.lastname}}</li>
    <li class="list-group-item">{{object.address}}</li>
    <li class="list-group-item">{{object.dob}}</li>
    <li class="list-group-item">{{object.email}}</li>
    <li class="list-group-item">{{object.phone}}</li>

    <ul class="list-group m-3">
        <p>Escuela:</p>
        <li class="list-group-item">{{object.escuela.name}}</li>
        <br>
        <p>Clases:</p>
        {% for clase in object.clase.all %}
            <li class="list-group-item">{{clase.name}}</li>
        {% endfor %}
    </ul>
    <form method="post" action="{% url 'student:delete' object.id %}">
        {% csrf_token %}
        <li class="list-group-item">
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a href="{% url 'student:list' %}" class="btn btn-info">Regresar</a>
        </li>
    </form>

</ul>
{% endblock %}

student/templates/student/student_form.html
{% extends 'student/base.html' %}

{% block content %}
<div class="mt-3">
    <form method="post"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary"> Guardar</button>
    </form>
</div>
{% endblock %}

student/templates/student/student_list.html
{% extends 'student/base.html' %}

{% block content %}
<div class="m-3">
    <div class="card">
        <div class="card-header">
            <a href="{% url 'student:new' %}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Agregar Estudiante</a>
        </div>
        <div class="body">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Nombres</th>
                    <th scope="col">Dirección</th>
                    <th scope="col">Email</th>
                    <th scope="col">Fecha de Nacimiento</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Acción</th>
                </tr>
                </thead>
                <tbody>
                {% for student in students %}
                <tr>
                    <td>{{student.name}} {{student.lastname}}</td>
                    <td>{{student.address}}</td>
                    <td>{{student.email}}</td>
                    <td>{{student.dob}}</td>
                    <td>{{student.phone}}</td>
                    <td class="text-center">
                        <a href="{% url 'student:detail' student.id %}">
                            <i class="fa fa-list-alt" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock %}